#!/usr/bin/env python

Import("env")

if env["platform"] == "xbox360":
    env.add_source_files(
        env.drivers_sources,
        [
            "dir_access_unix.cpp",
            "file_access_unix.cpp",
        ],
    )
else:
    env.add_source_files(env.drivers_sources, "*.cpp")

env["check_c_headers"] = [["mntent.h", "HAVE_MNTENT"]]
